import Head from 'next/head';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className="px-8 mt-10">
      <Head>
        <title>Create Next App!!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mx-auto lg:w-3/5 lg:flex lg:flex-row lg:h-auto">
        <img
          className="rounded-tr-md rounded-tr-md h-48 w-full lg:h-auto lg:w-2/5 lg:rounded-bl-none lg:rounded-tr-none"
          src="/image/furniture.jpeg"
          alt="loaded"
        />
        <div className="bg-white p-8 rounded-bl-md rounded-br-none lg:rounded-bl-none lg:rounded-tr-md">
          <h2 className="text-gray-700 font-semibold">
            Shift Overall look and fell by adding these Wonderfull touches to
            furniture in your home
          </h2>
          <p className="text-sm text-gray-600 mt-4">
            Ever Been In Your Room And Felt Like Something Was Missing?
            Persehaps It felt slightly bare and uninviting. i've got some simple
            tips to help you make any room feel complete.
          </p>
          <div className="flex items-center mt-8">
            <div className="flex items-center">
              <img
                className="h-10 w-10 rounded-full"
                src="/image/user.jpeg"
                alt="loaded"
              />
              <div className="ml-4">
                <p className="text-gray-800 text-sm font-semibold">
                  Michelle Appleton
                </p>
                <p className="text-gray-600 text-sm">28 Jun 2020</p>
              </div>
            </div>
            <div className="w-8 h-8 ml-auto rounded-full bg-gray-200 flex items-center justify-center">
              <svg
                viewBox="0 0 64 64"
                xmlns="http://www.w3.org/2000/svg"
                role="img"
                width="23"
                height="23"
              >
                <path
                  stroke-width="2"
                  stroke-miterlimit="10"
                  stroke-linecap="round"
                  stroke="#202020"
                  fill="#6E8098"
                  d="M32 22V10l28 20-28 20V38c-11.1 0-21.3.4-30 16 0-9.9 1-32 30-32z"
                  data-name="layer1"
                  stroke-linejoin="round"
                ></path>
              </svg>
            </div>
          </div>
        </div>
      </div>
      <div className="mx-auto lg:w-3/5 bg-white p-4 lg:rounded-br-md mb-3 lg:h-auto">
        <h1 className="text-lg text-gray-800 font-bold py-4"> 
        The heading should be clear and concise. ... </h1>
        <p className="text-gray-600">  It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. </p>
      </div>
    </div>
  );
}
